### PR TITLE
Add several spelling corrections

### PR DESCRIPTION
**Pull request by luzpaz**
separated them in to separate commits for better examination.

### CODE REVIEW

**Comment by luzpaz** [comment]
soft bump

**Comment by larsoner** [comment]
Travis is not happy

**Comment by luzpaz** [comment]
having trouble squashing these commits all in to one. Apologies for all the noise.

**Comment by luzpaz** [comment]
This PR should be good to go as well.

**Comment by larsoner** [comment]
Thanks @luzpaz

**Pull request merged**
