### PR TITLE
man page creation based on --help and --version output using help2man

### PR DESCRIPTION
**Pull request by cinemast**
Hi!

This is a pull-request for #25. I am using help2man and a include file to generate the manpage. Please review it, I think it could be useful for others too. This is how we generate the manpage of this project for Debian. So we could drop the additional steps and stick more closely to upstream :)

### CODE REVIEW

**Comment by anatol** [comment]
The changes look good to me. Tested and it works great.

**Comment by anatol** [comment]
More nitpicks:

 gzip requires '-f' as the file might already exist
 please remove trailing whitespaces from the files. Use `git diff @{u} --check` to detect it.

**Comment by cinemast** [comment]
I did add the -f option. But I could not find trailing whitespaces with the git command you suggested. Where did you find them?

**Comment by anatol** [comment]
After minor cleanup I pushed your changes to the repo. Thanks for your work!

**Pull request closed without merging**
