### PR TITLE
README: 'Sending Pull Requests' section added

### PR DESCRIPTION
**Pull request by luzpaz**
Added a section to educate folks about how to sort the dictionary.txt file in preparation for a PR.

### CODE REVIEW

**Comment by luzpaz** [comment]
Having a dickens of a time getting the RsT format correct. Apologies on the delay while i get this sorted out. Please hold merge till then.

**Comment by luzpaz** [comment]
@larsoner i can't ge tthe formatting to work. Do you mind lending a hand at your convenience ? Thanks!

**Comment by larsoner** [comment]
Is that what you were looking for?

**Comment by luzpaz** [comment]
Thanks! I consider it complete then. Feel free to merge whenever you choose appropriate.

**Pull request merged**
