### PR TITLE
Add new --regex option to set regular expression used to find words

### PR DESCRIPTION
**Pull request by thdot**
A new command line option `-r / --regex` is implemented to allow the user to set the regular expression which is used to find the words in the input lines. This is useful in projects where you want to overwrite the
default expression, for example to split words after an underscore like in `ID_ESTABLISED.`
The new regex option cannot be used together with the `--write-changes` functionality since it is not guarantied that this will not break code.
This PR is related to issue #6.

### CODE REVIEW

**Comment by pabs3** [comment]
The patch contains whitespace changes to code unrelated to the commit. I suggest putting that in a separate pull request.

**Comment by thdot** [comment]
I have updated the commit and removed the whitespace changes.

**Comment by thdot** [comment]
Friendly reminder-ping...

**Comment by thdot** [comment]
@lucasdemarchi: do you plan to integrate this feature in the future or is there a problem with this PR?
Some kind of feedback would be nice.

**Comment by lucasdemarchi** [comment]
@thdot sorry for the delay. Applied.

**Comment by thdot** [comment]
Great! Thank you.
I've created a new PR a few minutes ago :)

**Pull request merged**
