### PR TITLE
Enhance --dictionary option to allow multiple dictionaries

### PR DESCRIPTION
**Pull request by thdot**
Enhance the _--dictionary_ option so that multiple dictionary files can
be specified at the command line. With this feature projects can use 
the standard dictionary and in addition their own custom files.

### CODE REVIEW

**Comment by anatol** [comment]
Looks good to me

**Comment by thdot** [comment]
Sorry for adding the other commit to this request; this wasn't my intention.
Should I split them or do you wan't to merge them together?
What about the failed checks because of the annoying whitespaces in blank lines?

**Comment by thdot** [comment]
friendly reminder-ping...

**Comment by anatol** [comment]
Let's keep it as separate changes. It looks good to me. As there are no objections I am going to merge it.

Thank you Thorsten.

**Pull request merged**
