### PR TITLE
Remove a valid spelling that was being corrected (licenced->licensed)

### PR DESCRIPTION
**Pull request by peternewman**
Much as this pains me as a Brit, but both ced and sed are valid, e.g. http://www.dictionary.com/browse/licenced and https://en.oxforddictionaries.com/definition/licensed . Although also https://www.englishforums.com/English/LicencedOrLicensed/bgrjnb/post.htm .

My 2001 Oxford Dictionary includes both variants.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
What about the last comment in the third link?

> In AmE, "license" is both a noun and a verb.
> 
> In BrE, "licence" is the noun, and "license" is the verb (despite any comments to the contrary in this message thread).
> 
> Therefore, "licensed" is the ONLY correct spelling throughout the English-speaking world.
> 
> That being said, Canadians (at a rate far more than in the British Isles or elsewhere in the Commonwealth) with astounding frequency misspell the word as "licenced" (almost as bad as the Americans with "accomodation"). Canadian dictionaries point out that "licenced" is an alternative, but nonstandard, spelling, even in Canada. My hunch is that Canadians are employing a bit of "hyper British" spelling to distinguish it from American spelling, which in this case leads to Canadians often using the nonstandard spelling of "licenced."

http://www.wordreference.com/definition/licensed  lists "licence" as as noun only, not a verb, as does other dictionaries. Random House (dictionary.com) is the only dictionary I've seen that does not list "licence" as nonstandard.

**Comment by lucasdemarchi** [comment]
That been said, I don't think we should annoy people that argue it is correct and use it... So, I don't object if others think this should be applied.

**Comment by peternewman** [comment]
Hmm, personally I'd trust a paper dictionary over a literal anonymous person on the Internet (although you obviously need to trust what I'm saying regarding what's written in the dictionary).

This also ties into #103 .

**Comment by lucasdemarchi** [comment]
@peternewman agreed

**Comment by peternewman** [comment]
Can it be merged then @lucasdemarchi ? :smile:

**Comment by peternewman** [comment]
Thanks @larsoner

**Pull request merged**
