### PR TITLE
pep8 warnings fix + make clean

### PR DESCRIPTION
**Pull request by cinemast**
Fixed all pep8 warnings.
Added a clean target to the makefile.
chmod 755 for codespell target.

### CODE REVIEW

**Comment by anatol** [comment]
The changes look good to me. I am going to merge them. Lucs, do you have any objections?

**Comment by lucasdemarchi** [comment]
It's OK for me

**Comment by anatol** [comment]
The patch does not work:

$ ./codespell
  File "./codespell", line 41
    'data', 'dictionary.txt')
    ^
IndentationError: unexpected indent

**Comment by cinemast** [comment]
Sorry, I overlooked this. The latest commit should fix it.

**Comment by anatol** [comment]
Thanks for your fix. Though it is better to squash it into commit that introduced the regression. Plus the series need to be rebased on top of the recent codespell changes.

**Comment by cinemast** [comment]
squashed + rebased on current master.

**Comment by anatol** [comment]
Thanks! Merged.

**Pull request merged**
