### PR TITLE
MRG: Use setuptools for Windows

### LINKED ISSUE #82: There is no ./codespell.py
README says:

> Check usage with `./codespell.py -h`

But there is no `./codespell.py` (unless you cd into `bin`, in which case the command doesn't work either).

`codespell.py` was moved from `.` to `bin` in b400e4250d7342b76e361cfcf738da6f65fee035, but I don't understand why. The commit message is enigmatic.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #82.

### CODE REVIEW

**Comment by larsoner** [comment]
@lucasdemarchi can you enable AppVeyor for this repo? I don't think I have permissions to do so.

**Comment by larsoner** [comment]
@lucasdemarchi a gentle reminder to enable AppVeyor when you get a chance (or give me permissions (admin I think?) on this repo to do so)

**Comment by lucasdemarchi** [comment]
@larsoner giving admin permission is only available for organizations unfortunately

**Comment by lucasdemarchi** [comment]
I would be very happy to give you admin permissions though

**Comment by larsoner** [comment]
Ahh okay. Well for now just activating `AppVeyor` should be sufficient

**Comment by luzpaz** [comment]
could you not make a codespell/codespell organization ?

**Comment by larsoner** [comment]
@lucasdemarchi any chance to enable AppVeyor?

**Comment by luzpaz** [comment]
@lucasdemarchi ping

**Comment by lucasdemarchi** [comment]
@larsoner appveyor is registered for this project: https://ci.appveyor.com/project/lucasdemarchi/codespell

**Comment by larsoner** [comment]
Thanks @lucasdemarchi, looks like it's working and we can verify that #82 is fixed.

Feel free to have a look if you want. I'll merge tomorrow if I don't hear from anyone

**Pull request merged**
