### PR TITLE
Add 44 more words to dictionary.txt, and sort the lines.

### PR DESCRIPTION
**Pull request by qyearsley**
After adding a list of words, I ran sort | uniq on the list to sort it. This changed this position of some words that were already there -- is this OK?

The words that I added were misspellings that I've observed in source code:

absymal->abysmal
aleady->already
appeneded->appended
asssertion->assertion
becausee->because
characer->character
comonent->component
compair->compare
compairs->compares
construtor->constructor
curcumstance->circumstance
curcumstances->circumstances
derprecated->deprecated
destuction->destruction
elemenet->element
elemenets->elements
existance->existence
faciliate->facilitate
faciliates->facilitates
flakyness->flakiness
fragement->fragment
hexidecimal->hexadecimal
imcoming->incoming
initalize->initialize
initalizer->initializer
insensetive->insensitive
itnernal->internal
negligble->negligible
nonexistant->nonexistent
overlayed->overlaid
overriddden->overridden
partialy->partially
preferrable->preferable
refered->referred
representiative->representative
reproducabely->reproducibly
revison->revision
revisons->revisions
shashes->slashes
sonething->something
spurrious->spurious
subsytems->subsystems
sytems->systems
thier->their

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> After adding a list of words, I ran sort | uniq on the list to sort it. This changed this position of some words that were already there -- is this OK?

Please use "make sort-dictionary" since we use some arguments to sort that should be preserved

**Comment by qyearsley** [comment]
Done -- thanks for pointing that out :-)

**Comment by lucasdemarchi** [comment]
I did a quick review of the words and I'm ok with them. I'd prefer the 2 commits to be squashed into a single one, though.

**Comment by qyearsley** [comment]
Yay, finally figured out how to squash the commits in this pull request. Should be just one commit now :-)

**Pull request merged**
