### PR TITLE
Create a llvm toolchain exclude list

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by larsoner** [comment]
IMO these lists should live with individual projects rather than in the `codespell` repo. Eventually we could consider getting rid of the `mozilla` and `linux-kernel` lists even.

**Comment by sylvestre** [comment]
What is your concern?

**Comment by larsoner** [comment]
1. Maintenance burden / distribution. `llvm` maintainers are more qualified to say what should and shouldn't be included in such a list than `codespell` maintainers, and (related to this)
2. Scalability / separability. Imagine if every package started doing this, there would be many PRs to `codespell` rather than many PRs to their respective repos.

In terms of which words to include/exclude, I think the job of `codespell` should be to provide good defaults, and each package should then tweak their repos to fit their use cases.

**Comment by sylvestre** [comment]
I am a llvm maintainer too. I reused what has been used a few weeks ago on clang. @luzpaz 
but yeah, I understand your point.

**Comment by sylvestre** [comment]
I closed it. I created this PR for Mozilla:
https://github.com/lucasdemarchi/codespell/pull/454

Do you want me to remove the kernel list too?

**Comment by larsoner** [comment]
Nah, that one has been around for 2 years so it's more likely people are using it

**Pull request closed without merging**
