### PR TITLE
Add the packaging metadata to build the codespell snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest codespell in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

It was packaged and released to the store by @royabouhamad during [google code-in](https://codein.withgoogle.com/). So, when you try to register the name you will find that it is already taken. You just have to fill the form claiming that you are the upstream developer, and we will take care of the transfer.

### CODE REVIEW

**Comment by larsoner** [comment]
@lucasdemarchi okay with you to proceed with this?

**Comment by larsoner** [comment]
@royabouhamad have you communicated with @lucasdemarchi about this already separately?

**Comment by royabouhamad** [comment]
No, what do I need to tell him?

**Comment by larsoner** [comment]
I just want to make sure he's okay with it. That's why I posted above asking him if he's okay with it (and why I was confused when you responded for him).

**Comment by larsoner** [comment]
No objections from @lucasdemarchi so I'll merge, thanks @elopio

**Pull request merged**
