### PR TITLE
Fix install rule

### LINKED ISSUE #43: make install fails to create codespell from codespell.py
vagrant@debian:~/.codespell (master)$ make install
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1
vagrant@debian:~/.codespell (master)$ make sort-dictionary
LANG=C sort -f -u -o data/dictionary.txt data/dictionary.txt
vagrant@debian:~/.codespell (master)$ make install --debug=v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
Reading makefiles...
Reading makefile `Makefile'...
Updating goal targets....
Considering target file `install'.
 File `install' does not exist.
  Considering target file `codespell'.
   File `codespell' does not exist.
    Considering target file `codespell.py'.
     Finished prerequisites of target file `codespell.py'.
    No need to remake target `codespell.py'.
    Considering target file `check-dictionary'.
     File `check-dictionary' does not exist.
     Finished prerequisites of target file `check-dictionary'.
    Must remake target `check-dictionary'.
sort: data/dictionary.txt:274: disorder: Amercia->America
Dictionary not sorted. Sort with 'make sort-dictionary'
make: *** [check-dictionary] Error 1
vagrant@debian:~/.codespell (master)$ ./codespell
-bash: ./codespell: No such file or directory
vagrant@debian:~/.codespell (master)$ ls -lA
total 72
-rw-r--r-- 1 vagrant vagrant   439 Sep  9 21:25 codespell.1.include
-rwxr-xr-x 1 vagrant vagrant 17900 Sep  9 21:25 codespell.py
-rw-r--r-- 1 vagrant vagrant 18092 Sep  9 21:25 COPYING
drwxr-xr-x 2 vagrant vagrant  4096 Sep  9 21:25 data
drwxr-xr-x 2 vagrant vagrant  4096 Sep  9 21:25 example
drwxr-xr-x 8 vagrant vagrant  4096 Sep  9 21:26 .git
-rw-r--r-- 1 vagrant vagrant  2223 Sep  9 21:25 Makefile
-rw-r--r-- 1 vagrant vagrant   294 Sep  9 21:25 NEWS
-rw-r--r-- 1 vagrant vagrant  3035 Sep  9 21:25 README.md
-rw-r--r-- 1 vagrant vagrant   107 Sep  9 21:25 TODO

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Fix #43

### CODE REVIEW

**Comment by uberhacker** [comment]
Hey Lucas,
Thanks for the quick response.  The patch works!  Still get dictionary error, however.

vagrant@debian:~/.codespell (master *)$ codespell
ERROR: cannot find dictionary file!

**Comment by lucasdemarchi** [comment]
Where are you installing to? Are you running codespell from that location?

**Comment by uberhacker** [comment]
I cloned the repo into ~/.codespell and added an alias in .bash_aliases:

alias codespell='$HOME/.codespell/codespell'

**Comment by lucasdemarchi** [comment]
This won't work. The install rule is there only to install on /usr  so it's easy for Linux distros to create packages.

What you want to do can be done without running the install rule:
```
alias codespell=$HOME/.codespell/codespell.py
```

**Comment by uberhacker** [comment]
Yeah, I could do that.  Where should the codespell executable reside after
sudo make install?  It installs inside my repo directory currently.

vagrant@debian:~/.codespell (master *)$ sudo make install
sed "s|^default_dictionary = .*|default_dictionary =
'/usr/local/share/codespell/dictionary.txt'|" < codespell.py > codespell
chmod 755 codespell
help2man ./codespell --include codespell.1.include --no-info --output
codespell.1
make: help2man: Command not found
make: *** [manpage] Error 127
vagrant@debian:~/.codespell (master *)$ ls -lA
total 92
-rwxr-xr-x 1 root    root    17860 Sep  9 22:26 codespell


On Wed, Sep 9, 2015 at 5:24 PM, Lucas De Marchi <notifications@github.com>
wrote:

> This won't work. The install rule is there only to install on /usr so it's
> easy for Linux distros to create packages.
>
> What you want to do can be done without running the install rule:
>
> alias codespell=$HOME/.codespell/codespell.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasdemarchi/codespell/pull/44#issuecomment-139062151>
> .
>



-- 
"God gave us two ears and one mouth to remind us we should listen twice as
much as we talk."

**Comment by lucasdemarchi** [comment]
by default in /usr/local/bin. But it's failing for you because you don't have the help2man tool.

**Comment by uberhacker** [comment]
Should that be mentioned in the requirements?

On Wed, Sep 9, 2015 at 6:32 PM, Lucas De Marchi <notifications@github.com>
wrote:

> by default in /usr/local/bin. But it's failing for you because you don't
> have the help2man tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucasdemarchi/codespell/pull/44#issuecomment-139072349>
> .
>



-- 
"God gave us two ears and one mouth to remind us we should listen twice as
much as we talk."

**Comment by lucasdemarchi** [comment]
Fixed by #45

**Pull request closed without merging**
